onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_data_block/SYSCLK
add wave -noupdate /tb_data_block/CTRL_enable_cmd
add wave -noupdate /tb_data_block/CTRL_write_read
add wave -noupdate /tb_data_block/CTRL_busy
add wave -noupdate /tb_data_block/CTRL_addr_frame
add wave -noupdate /tb_data_block/CTRL_write_data_frame
add wave -noupdate /tb_data_block/CTRL_read_data_frame
add wave -noupdate /tb_data_block/Communication_Read
add wave -noupdate /tb_data_block/Communication_Builder_RUN
add wave -noupdate /tb_data_block/Communication_Empty
add wave -noupdate /tb_data_block/Communication_Data_Frame
add wave -noupdate /tb_data_block/Communication_Data_Req
add wave -noupdate /tb_data_block/Control_Fifo_Data
add wave -noupdate /tb_data_block/Control_Fifo_Empty
add wave -noupdate /tb_data_block/Control_Fifo_RE
add wave -noupdate /tb_data_block/TX_Fifo_Full
add wave -noupdate /tb_data_block/TX_Fifo_WE
add wave -noupdate /tb_data_block/TX_Fifo_Data
add wave -noupdate /tb_data_block/Data_Valid
add wave -noupdate /tb_data_block/data_for_store
add wave -noupdate /tb_data_block/Data_Block_0/Trigger_Top_Part_0/Trigger_Main_0/Trigger_Edge_Valid
add wave -noupdate /tb_data_block/Data_Block_0/Trigger_Top_Part_0/Trigger_Main_0/state_reg
add wave -noupdate /tb_data_block/Data_Block_0/Trigger_Top_Part_0/Trigger_Main_0/SampleTactCounter_Reset
add wave -noupdate /tb_data_block/Data_Block_0/Trigger_Top_Part_0/Trigger_Main_0/SampleTactCounter_Enable
add wave -noupdate /tb_data_block/Data_Block_0/Trigger_Top_Part_0/Trigger_Main_0/ACQ_LastSampleTact
add wave -noupdate /tb_data_block/Data_Block_0/Trigger_Top_Part_0/Trigger_Main_0/SampleTactCounter
add wave -noupdate /tb_data_block/Data_Block_0/Trigger_Top_Part_0/ALL_FIFO_Write
add wave -noupdate /tb_data_block/Data_Block_0/Trigger_Top_Part_0/Trigger_Main_0_FIFO_Event_Data
add wave -noupdate /tb_data_block/Data_Block_0/Input_Data_Part_1/Trigger_Unit_3_Output_Data
add wave -noupdate /tb_data_block/Data_Block_0/Input_Data_Part_1/Trigger_Unit_2_Output_Data
add wave -noupdate /tb_data_block/Data_Block_0/Input_Data_Part_1/Trigger_Unit_1_Output_Data
add wave -noupdate /tb_data_block/Data_Block_0/Input_Data_Part_1/Trigger_Unit_0_Output_Data
add wave -noupdate /tb_data_block/Data_Block_0/Input_Data_Part_0/Trigger_Unit_3_Output_Data
add wave -noupdate /tb_data_block/Data_Block_0/Input_Data_Part_0/Trigger_Unit_2_Output_Data
add wave -noupdate /tb_data_block/Data_Block_0/Input_Data_Part_0/Trigger_Unit_1_Output_Data
add wave -noupdate /tb_data_block/Data_Block_0/Input_Data_Part_0/Trigger_Unit_0_Output_Data
add wave -noupdate /tb_data_block/Data_Block_0/FIFOs_Reader_0/state_reg
add wave -noupdate /tb_data_block/Data_Block_0/FIFOs_Reader_0/Data_MUX_Sel
add wave -noupdate /tb_data_block/Data_Block_0/FIFOs_Reader_0/Sample_RAM_W_Data
add wave -noupdate /tb_data_block/Data_Block_0/FIFOs_Reader_0/Event_RAM_W_Enable_Start_ADDR
add wave -noupdate /tb_data_block/Data_Block_0/FIFOs_Reader_0/Event_RAM_W_Enable_Size
add wave -noupdate /tb_data_block/Data_Block_0/FIFOs_Reader_0/Event_RAM_W_Enable_Number
add wave -noupdate /tb_data_block/Data_Block_0/FIFOs_Reader_0/Event_RAM_W_Enable_Status
add wave -noupdate /tb_data_block/Data_Block_0/FIFOs_Reader_0/Event_RAM_W_Data_Start_ADDR
add wave -noupdate -radix ufixed /tb_data_block/Data_Block_0/FIFOs_Reader_0/Event_RAM_W_Data_Size
add wave -noupdate /tb_data_block/Data_Block_0/FIFOs_Reader_0/Event_RAM_W_Data_Number
add wave -noupdate /tb_data_block/Data_Block_0/FIFOs_Reader_0/Event_RAM_W_Data_Status
add wave -noupdate /tb_data_block/Data_Block_0/Communication_Builder_0/state_reg
add wave -noupdate /tb_data_block/Data_Block_0/Communication_Builder_0/wait_next_state
add wave -noupdate /tb_data_block/Data_Block_0/Communication_Builder_0/next_state
add wave -noupdate /tb_data_block/Data_Block_0/Communication_Builder_0/Sample_RAM_R_Address
add wave -noupdate /tb_data_block/Data_Block_0/Communication_Builder_0/Sample_RAM_R_Data
add wave -noupdate /tb_data_block/Data_Block_0/Communication_Builder_0/Communication_Data_Frame_F
add wave -noupdate /tb_data_block/Data_Block_0/Communication_Builder_0/Read_Sample_3
add wave -noupdate /tb_data_block/Data_Block_0/Communication_Builder_0/Read_Sample_2
add wave -noupdate /tb_data_block/Data_Block_0/Communication_Builder_0/Read_Sample_1
add wave -noupdate /tb_data_block/Data_Block_0/Communication_Builder_0/Read_Sample_0
add wave -noupdate /tb_data_block/Data_Block_0/Communication_Builder_0/Sample_Buffer_Store
add wave -noupdate /tb_data_block/Data_Block_0/Communication_Builder_0/Sample_RAM_ADDR_GEN_Modulo
add wave -noupdate /tb_data_block/Data_Block_0/Communication_Builder_0/Sample_RAM_ADDR_GEN_Init
add wave -noupdate /tb_data_block/Data_Block_0/Communication_Builder_0/Sample_RAM_ADDR_GEN_Enable
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {6380232 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 336
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {6359003 ps} {6423049 ps}
