# Netlist Viewer TCL File
set_family -name PolarFire
top_module -name Top
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/AnalyzInCirc_Controler.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/AnalyzInCirc_FIFO.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/AnalyzInCirc_Top.vhd}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/CORERESET_PF_C0/CORERESET_PF_C0_0/core/corereset_pf.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/CORERESET_PF_C0/CORERESET_PF_C0.v}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/Clock_Controller.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/Synchronizer.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/Clock_Switch.vhd}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/PF_CCC_C0/PF_CCC_C0_0/PF_CCC_C0_PF_CCC_C0_0_PF_CCC.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/PF_CCC_C0/PF_CCC_C0.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/PF_CCC_C3/PF_CCC_C3_0/PF_CCC_C3_PF_CCC_C3_0_PF_CCC.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/PF_CCC_C3/PF_CCC_C3.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/PF_CCC_C7/PF_CCC_C7_0/PF_CCC_C7_PF_CCC_C7_0_PF_CCC.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/PF_CCC_C7/PF_CCC_C7.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/PF_CLK_DIV_C2/PF_CLK_DIV_C2_0/PF_CLK_DIV_C2_PF_CLK_DIV_C2_0_PF_CLK_DIV.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/PF_CLK_DIV_C2/PF_CLK_DIV_C2.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/PF_INIT_MONITOR_C0/PF_INIT_MONITOR_C0_0/PF_INIT_MONITOR_C0_PF_INIT_MONITOR_C0_0_PF_INIT_MONITOR.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/PF_INIT_MONITOR_C0/PF_INIT_MONITOR_C0.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/PF_OSC_C0/PF_OSC_C0_0/PF_OSC_C0_PF_OSC_C0_0_PF_OSC.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/PF_OSC_C0/PF_OSC_C0.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/Clock_Reset/Clock_Reset.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C1/COREFIFO_C1_0/rtl/vlog/core/corefifo_NstagesSync.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C1/COREFIFO_C1_0/rtl/vlog/core/corefifo_grayToBinConv.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C1/COREFIFO_C1_0/rtl/vlog/core/corefifo_async.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C1/COREFIFO_C1_0/rtl/vlog/core/corefifo_fwft.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C1/COREFIFO_C1_0/rtl/vlog/core/corefifo_sync.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C1/COREFIFO_C1_0/rtl/vlog/core/corefifo_sync_scntr.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C1/COREFIFO_C1_0/rtl/vlog/core/COREFIFO_C1_COREFIFO_C1_0_LSRAM_top.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C1/COREFIFO_C1_0/rtl/vlog/core/COREFIFO_C1_COREFIFO_C1_0_ram_wrapper.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C1/COREFIFO_C1_0/rtl/vlog/core/COREFIFO.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C1/COREFIFO_C1.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C3/COREFIFO_C3_0/rtl/vlog/core/corefifo_NstagesSync.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C3/COREFIFO_C3_0/rtl/vlog/core/corefifo_grayToBinConv.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C3/COREFIFO_C3_0/rtl/vlog/core/corefifo_async.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C3/COREFIFO_C3_0/rtl/vlog/core/corefifo_fwft.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C3/COREFIFO_C3_0/rtl/vlog/core/corefifo_sync.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C3/COREFIFO_C3_0/rtl/vlog/core/corefifo_sync_scntr.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C3/COREFIFO_C3_0/rtl/vlog/core/COREFIFO_C3_COREFIFO_C3_0_LSRAM_top.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C3/COREFIFO_C3_0/rtl/vlog/core/COREFIFO_C3_COREFIFO_C3_0_ram_wrapper.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C3/COREFIFO_C3_0/rtl/vlog/core/COREFIFO.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C3/COREFIFO_C3.v}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/Communication_ANW_MUX.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/Communication_CMD_MUX.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/Communication_Controler.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/Communication_Switch.vhd}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C0/COREFIFO_C0_0/rtl/vlog/core/corefifo_sync_scntr.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C0/COREFIFO_C0_0/rtl/vlog/core/corefifo_sync.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C0/COREFIFO_C0_0/rtl/vlog/core/corefifo_NstagesSync.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C0/COREFIFO_C0_0/rtl/vlog/core/corefifo_grayToBinConv.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C0/COREFIFO_C0_0/rtl/vlog/core/corefifo_async.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C0/COREFIFO_C0_0/rtl/vlog/core/corefifo_fwft.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C0/COREFIFO_C0_0/rtl/vlog/core/COREFIFO_C0_COREFIFO_C0_0_LSRAM_top.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C0/COREFIFO_C0_0/rtl/vlog/core/COREFIFO_C0_COREFIFO_C0_0_ram_wrapper.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C0/COREFIFO_C0_0/rtl/vlog/core/COREFIFO.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C0/COREFIFO_C0.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C6/COREFIFO_C6_0/rtl/vlog/core/corefifo_NstagesSync.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C6/COREFIFO_C6_0/rtl/vlog/core/corefifo_grayToBinConv.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C6/COREFIFO_C6_0/rtl/vlog/core/corefifo_async.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C6/COREFIFO_C6_0/rtl/vlog/core/corefifo_sync.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C6/COREFIFO_C6_0/rtl/vlog/core/corefifo_fwft.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C6/COREFIFO_C6_0/rtl/vlog/core/corefifo_sync_scntr.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C6/COREFIFO_C6_0/rtl/vlog/core/COREFIFO_C6_COREFIFO_C6_0_LSRAM_top.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C6/COREFIFO_C6_0/rtl/vlog/core/COREFIFO_C6_COREFIFO_C6_0_ram_wrapper.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C6/COREFIFO_C6_0/rtl/vlog/core/COREFIFO.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C6/COREFIFO_C6.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREUART_C0/COREUART_C0_0/rtl/vlog/core/Clock_gen.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREUART_C0/COREUART_C0_0/rtl/vlog/core/Rx_async.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREUART_C0/COREUART_C0_0/rtl/vlog/core/Tx_async.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREUART_C0/COREUART_C0_0/rtl/vlog/core/fifo_256x8_54sxa.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREUART_C0/COREUART_C0_0/rtl/vlog/core/CoreUART.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREUART_C0/COREUART_C0.v}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/Communication_TX_Arbiter2.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/UART_RX_Protocol.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/UART_TX_Protocol.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/mko.vhd}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/UART_Protocol/UART_Protocol.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C11/COREFIFO_C11_0/rtl/vlog/core/corefifo_NstagesSync.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C11/COREFIFO_C11_0/rtl/vlog/core/corefifo_grayToBinConv.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C11/COREFIFO_C11_0/rtl/vlog/core/corefifo_async.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C11/COREFIFO_C11_0/rtl/vlog/core/corefifo_sync.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C11/COREFIFO_C11_0/rtl/vlog/core/corefifo_fwft.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C11/COREFIFO_C11_0/rtl/vlog/core/corefifo_sync_scntr.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C11/COREFIFO_C11_0/rtl/vlog/core/COREFIFO_C11_COREFIFO_C11_0_LSRAM_top.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C11/COREFIFO_C11_0/rtl/vlog/core/COREFIFO_C11_COREFIFO_C11_0_ram_wrapper.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C11/COREFIFO_C11_0/rtl/vlog/core/COREFIFO.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C11/COREFIFO_C11.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C7/COREFIFO_C7_0/rtl/vlog/core/corefifo_sync_scntr.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C7/COREFIFO_C7_0/rtl/vlog/core/corefifo_sync.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C7/COREFIFO_C7_0/rtl/vlog/core/corefifo_NstagesSync.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C7/COREFIFO_C7_0/rtl/vlog/core/corefifo_grayToBinConv.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C7/COREFIFO_C7_0/rtl/vlog/core/corefifo_async.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C7/COREFIFO_C7_0/rtl/vlog/core/corefifo_fwft.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C7/COREFIFO_C7_0/rtl/vlog/core/COREFIFO_C7_COREFIFO_C7_0_LSRAM_top.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C7/COREFIFO_C7_0/rtl/vlog/core/COREFIFO_C7_COREFIFO_C7_0_ram_wrapper.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C7/COREFIFO_C7_0/rtl/vlog/core/COREFIFO.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C7/COREFIFO_C7.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C8/COREFIFO_C8_0/rtl/vlog/core/corefifo_fwft.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C8/COREFIFO_C8_0/rtl/vlog/core/corefifo_sync_scntr.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C8/COREFIFO_C8_0/rtl/vlog/core/corefifo_sync.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C8/COREFIFO_C8_0/rtl/vlog/core/corefifo_NstagesSync.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C8/COREFIFO_C8_0/rtl/vlog/core/corefifo_grayToBinConv.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C8/COREFIFO_C8_0/rtl/vlog/core/corefifo_async.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C8/COREFIFO_C8_0/rtl/vlog/core/COREFIFO_C8_COREFIFO_C8_0_LSRAM_top.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C8/COREFIFO_C8_0/rtl/vlog/core/COREFIFO_C8_COREFIFO_C8_0_ram_wrapper.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C8/COREFIFO_C8_0/rtl/vlog/core/COREFIFO.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C8/COREFIFO_C8.v}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/ft601_fifo_interface.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/ftdi_to_fifo_interface.vhd}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/USB_3_Protocol/USB_3_Protocol.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/Communication/Communication.v}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/ADI_SPI.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/cmd_table.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/Answer_Encoder.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/Command_Decoder.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/REGISTERS.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/Reset_Controler.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/SPI_interface.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/spi_master.vhd}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/SPI_LMX/SPI_LMX.v}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/gpio_controler.vhd}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/Controler/Controler.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C10/COREFIFO_C10_0/rtl/vlog/core/corefifo_fwft.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C10/COREFIFO_C10_0/rtl/vlog/core/corefifo_sync_scntr.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C10/COREFIFO_C10_0/rtl/vlog/core/corefifo_sync.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C10/COREFIFO_C10_0/rtl/vlog/core/corefifo_NstagesSync.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C10/COREFIFO_C10_0/rtl/vlog/core/corefifo_grayToBinConv.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C10/COREFIFO_C10_0/rtl/vlog/core/corefifo_async.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C10/COREFIFO_C10_0/rtl/vlog/core/COREFIFO_C10_COREFIFO_C10_0_LSRAM_top.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C10/COREFIFO_C10_0/rtl/vlog/core/COREFIFO_C10_COREFIFO_C10_0_ram_wrapper.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C10/COREFIFO_C10_0/rtl/vlog/core/COREFIFO.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C10/COREFIFO_C10.v}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/Communication_Builder.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/CtrlBus_HandShake.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/DataRamManage.vhd}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/PF_DPSRAM_C7/PF_DPSRAM_C7_0/PF_DPSRAM_C7_PF_DPSRAM_C7_0_PF_DPSRAM.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/PF_DPSRAM_C7/PF_DPSRAM_C7.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/PF_DPSRAM_C8_Event_Status/PF_DPSRAM_C8_Event_Status_0/PF_DPSRAM_C8_Event_Status_PF_DPSRAM_C8_Event_Status_0_PF_DPSRAM.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/PF_DPSRAM_C8_Event_Status/PF_DPSRAM_C8_Event_Status.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/Event_Info_RAM_Block/Event_Info_RAM_Block.v}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/FIFOs_Reader.vhd}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C4/COREFIFO_C4_0/rtl/vlog/core/corefifo_NstagesSync.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C4/COREFIFO_C4_0/rtl/vlog/core/corefifo_grayToBinConv.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C4/COREFIFO_C4_0/rtl/vlog/core/corefifo_async.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C4/COREFIFO_C4_0/rtl/vlog/core/corefifo_sync.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C4/COREFIFO_C4_0/rtl/vlog/core/corefifo_fwft.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C4/COREFIFO_C4_0/rtl/vlog/core/corefifo_sync_scntr.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C4/COREFIFO_C4_0/rtl/vlog/core/COREFIFO_C4_COREFIFO_C4_0_LSRAM_top.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C4/COREFIFO_C4_0/rtl/vlog/core/COREFIFO_C4_COREFIFO_C4_0_ram_wrapper.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C4/COREFIFO_C4_0/rtl/vlog/core/COREFIFO.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C4/COREFIFO_C4.v}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/Trigger_Unit.vhd}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/Input_Data_Part/Input_Data_Part.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/PF_DPSRAM_C5/PF_DPSRAM_C5_0/PF_DPSRAM_C5_PF_DPSRAM_C5_0_PF_DPSRAM.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/PF_DPSRAM_C5/PF_DPSRAM_C5.v}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/Sample_RAM_Block_Decoder.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/Sample_RAM_Block_MUX.vhd}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/Sample_RAM_Block/Sample_RAM_Block.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C5/COREFIFO_C5_0/rtl/vlog/core/corefifo_NstagesSync.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C5/COREFIFO_C5_0/rtl/vlog/core/corefifo_grayToBinConv.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C5/COREFIFO_C5_0/rtl/vlog/core/corefifo_async.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C5/COREFIFO_C5_0/rtl/vlog/core/corefifo_sync.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C5/COREFIFO_C5_0/rtl/vlog/core/corefifo_fwft.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C5/COREFIFO_C5_0/rtl/vlog/core/corefifo_sync_scntr.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C5/COREFIFO_C5_0/rtl/vlog/core/COREFIFO_C5_COREFIFO_C5_0_LSRAM_top.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C5/COREFIFO_C5_0/rtl/vlog/core/COREFIFO_C5_COREFIFO_C5_0_ram_wrapper.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C5/COREFIFO_C5_0/rtl/vlog/core/COREFIFO.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C5/COREFIFO_C5.v}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/cmd_table_trigger.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/Trigger_Control.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/Trigger_Main.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/EventFifoFreeLogic.vhd}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/Trigger_Top_Part/Trigger_Top_Part.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/Data_Block/Data_Block.v}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/EXT_Signals_Controller.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/EXT_Signals_OutputSwitch.vhd}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/Actel/SgCore/PF_IO/2.0.104/core/vlog/PF_IO.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/PF_IO_C0/PF_IO_C0.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/EXT_Signals/EXT_Signals.v}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/SampleCompose.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/SampleTxDeCompose.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/Test_Generator_for_Lanes.vhd}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C12/COREFIFO_C12_0/rtl/vlog/core/corefifo_sync_scntr.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C12/COREFIFO_C12_0/rtl/vlog/core/corefifo_sync.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C12/COREFIFO_C12_0/rtl/vlog/core/corefifo_NstagesSync.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C12/COREFIFO_C12_0/rtl/vlog/core/corefifo_grayToBinConv.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C12/COREFIFO_C12_0/rtl/vlog/core/corefifo_async.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C12/COREFIFO_C12_0/rtl/vlog/core/corefifo_fwft.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C12/COREFIFO_C12_0/rtl/vlog/core/COREFIFO_C12_COREFIFO_C12_0_LSRAM_top.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C12/COREFIFO_C12_0/rtl/vlog/core/COREFIFO_C12_COREFIFO_C12_0_ram_wrapper.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C12/COREFIFO_C12_0/rtl/vlog/core/COREFIFO.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C12/COREFIFO_C12.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C13/COREFIFO_C13_0/rtl/vlog/core/corefifo_sync_scntr.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C13/COREFIFO_C13_0/rtl/vlog/core/corefifo_sync.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C13/COREFIFO_C13_0/rtl/vlog/core/corefifo_NstagesSync.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C13/COREFIFO_C13_0/rtl/vlog/core/corefifo_grayToBinConv.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C13/COREFIFO_C13_0/rtl/vlog/core/corefifo_async.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C13/COREFIFO_C13_0/rtl/vlog/core/corefifo_fwft.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C13/COREFIFO_C13_0/rtl/vlog/core/COREFIFO_C13_COREFIFO_C13_0_LSRAM_top.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C13/COREFIFO_C13_0/rtl/vlog/core/COREFIFO_C13_COREFIFO_C13_0_ram_wrapper.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C13/COREFIFO_C13_0/rtl/vlog/core/COREFIFO.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/COREFIFO_C13/COREFIFO_C13.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/PF_TX_PLL_C1/PF_TX_PLL_C1_0/PF_TX_PLL_C1_PF_TX_PLL_C1_0_PF_TX_PLL.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/PF_TX_PLL_C1/PF_TX_PLL_C1.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/Actel/DirectCore/CORELCKMGT/2.0.100/rtl/vlog/core/CORELCKMGT.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/Actel/DirectCore/CORERFD/2.1.100/rtl/vlog/core/CORERFDgrycnt.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/Actel/DirectCore/CORERFD/2.1.100/rtl/vlog/core/CORERFDbincnt.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/Actel/DirectCore/CORERFD/2.1.100/rtl/vlog/core/CORERFDsmplcnt.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/Actel/DirectCore/CORERFD/2.1.100/rtl/vlog/core/CORERFDfrqerrarb.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/Actel/DirectCore/CORERFD/2.1.100/rtl/vlog/core/CORERFDplsgen.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/Actel/DirectCore/CORERFD/2.1.100/rtl/vlog/core/CORERFDshcnt.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/Actel/DirectCore/CORERFD/2.1.100/rtl/vlog/core/CORERFDsyncen.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/Actel/DirectCore/CORERFD/2.1.100/rtl/vlog/core/CORERFDsync.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/Actel/DirectCore/CORERFD/2.1.100/rtl/vlog/core/CORERFDsicr.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/Actel/DirectCore/CORERFD/2.1.100/rtl/vlog/core/CORERFD.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/Actel/SgCore/PF_XCVR_APBLINK_V/1.1.104/hdl/PF_XCVR_APBLINK_V.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/PF_XCVR_ERM_C8/I_XCVR/PF_XCVR_ERM_C8_I_XCVR_PF_XCVR.v}
addfile -view RTL -lib work -type VLOG -mode VLOG_INC_DIR -name {C:\VHDL_temp\Digitizer\Digitizer_vhdl\Digitizer\component\Actel\DirectCore\CORELANEMSTR\2.1.100\rtl\vlog\core}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/Actel/DirectCore/CORELANEMSTR/2.1.100/rtl/vlog/core/CORELANEMSTRmode0.v}
addfile -view RTL -lib work -type VLOG -mode VLOG_INC_DIR -name {C:\VHDL_temp\Digitizer\Digitizer_vhdl\Digitizer\component\Actel\DirectCore\CORELANEMSTR\2.1.100\rtl\vlog\core}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/Actel/DirectCore/CORELANEMSTR/2.1.100/rtl/vlog/core/CORELANEMSTRmode1.v}
addfile -view RTL -lib work -type VLOG -mode VLOG_INC_DIR -name {C:\VHDL_temp\Digitizer\Digitizer_vhdl\Digitizer\component\Actel\DirectCore\CORELANEMSTR\2.1.100\rtl\vlog\core}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/Actel/DirectCore/CORELANEMSTR/2.1.100/rtl/vlog/core/CORELANEMSTRmode2.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/Actel/DirectCore/CORELANEMSTR/2.1.100/rtl/vlog/core/CORELANEMSTR.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/PF_XCVR_ERM_C8/PF_XCVR_ERM_C8.v}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/Transceiver_LaneStatus.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/AlignmentLane_Fifo.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/RxLaneControl.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/TxLaneControl.vhd}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/Transciever_OneLane/Transciever_OneLane.v}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/RxMainLinkController.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/TxMainLinkController.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/Transceiver_LanesConnection.vhd}
addfile -view RTL -lib work -type VHDL -mode vhdl_2008 -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/hdl/Transceiver_Controller.vhd}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/Transceiver_Main/Transceiver_Main.v}
addfile -view RTL -lib work -type VLOG -mode system_verilog -name {C:/VHDL_temp/Digitizer/Digitizer_vhdl/Digitizer/component/work/Top/Top.v}