set_device -family {PolarFire} -die {MPF300TS_ES} -speed {-1}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\CORERESET_PF_C0\CORERESET_PF_C0_0\core\corereset_pf.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\CORERESET_PF_C0\CORERESET_PF_C0.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\PF_CCC_C0\PF_CCC_C0_0\PF_CCC_C0_PF_CCC_C0_0_PF_CCC.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\PF_CCC_C0\PF_CCC_C0.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\PF_INIT_MONITOR_C0\PF_INIT_MONITOR_C0_0\PF_INIT_MONITOR_C0_PF_INIT_MONITOR_C0_0_PF_INIT_MONITOR.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\PF_INIT_MONITOR_C0\PF_INIT_MONITOR_C0.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\PF_OSC_C0\PF_OSC_C0_0\PF_OSC_C0_PF_OSC_C0_0_PF_OSC.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\PF_OSC_C0\PF_OSC_C0.v}
read_vhdl -mode vhdl_2008 {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\hdl\Synchronizer.vhd}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\Clock_Reset\Clock_Reset.v}
read_vhdl -mode vhdl_2008 {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\hdl\ADI_SPI.vhd}
read_vhdl -mode vhdl_2008 {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\hdl\cmd_table.vhd}
read_vhdl -mode vhdl_2008 {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\hdl\Answer_Encoder.vhd}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C1\COREFIFO_C1_0\rtl\vlog\core\corefifo_NstagesSync.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C1\COREFIFO_C1_0\rtl\vlog\core\corefifo_grayToBinConv.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C1\COREFIFO_C1_0\rtl\vlog\core\corefifo_async.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C1\COREFIFO_C1_0\rtl\vlog\core\corefifo_fwft.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C1\COREFIFO_C1_0\rtl\vlog\core\corefifo_sync.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C1\COREFIFO_C1_0\rtl\vlog\core\corefifo_sync_scntr.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C1\COREFIFO_C1_0\rtl\vlog\core\COREFIFO_C1_COREFIFO_C1_0_LSRAM_top.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C1\COREFIFO_C1_0\rtl\vlog\core\COREFIFO_C1_COREFIFO_C1_0_ram_wrapper.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C1\COREFIFO_C1_0\rtl\vlog\core\COREFIFO.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C1\COREFIFO_C1.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C3\COREFIFO_C3_0\rtl\vlog\core\corefifo_NstagesSync.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C3\COREFIFO_C3_0\rtl\vlog\core\corefifo_grayToBinConv.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C3\COREFIFO_C3_0\rtl\vlog\core\corefifo_async.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C3\COREFIFO_C3_0\rtl\vlog\core\corefifo_fwft.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C3\COREFIFO_C3_0\rtl\vlog\core\corefifo_sync.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C3\COREFIFO_C3_0\rtl\vlog\core\corefifo_sync_scntr.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C3\COREFIFO_C3_0\rtl\vlog\core\COREFIFO_C3_COREFIFO_C3_0_LSRAM_top.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C3\COREFIFO_C3_0\rtl\vlog\core\COREFIFO_C3_COREFIFO_C3_0_ram_wrapper.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C3\COREFIFO_C3_0\rtl\vlog\core\COREFIFO.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C3\COREFIFO_C3.v}
read_vhdl -mode vhdl_2008 {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\hdl\Command_Decoder.vhd}
read_vhdl -mode vhdl_2008 {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\hdl\Communication_ANW_MUX.vhd}
read_vhdl -mode vhdl_2008 {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\hdl\Communication_CMD_MUX.vhd}
read_vhdl -mode vhdl_2008 {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\hdl\REGISTERS.vhd}
read_vhdl -mode vhdl_2008 {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\hdl\System_Controler.vhd}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\Controler\Controler.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\PF_DPSRAM_C7\PF_DPSRAM_C7_0\PF_DPSRAM_C7_PF_DPSRAM_C7_0_PF_DPSRAM.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\PF_DPSRAM_C7\PF_DPSRAM_C7.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\PF_DPSRAM_C8_Event_Status\PF_DPSRAM_C8_Event_Status_0\PF_DPSRAM_C8_Event_Status_PF_DPSRAM_C8_Event_Status_0_PF_DPSRAM.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\PF_DPSRAM_C8_Event_Status\PF_DPSRAM_C8_Event_Status.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\Event_Info_RAM_Block\Event_Info_RAM_Block.v}
read_vhdl -mode vhdl_2008 {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\hdl\FIFOs_Reader.vhd}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C4\COREFIFO_C4_0\rtl\vlog\core\corefifo_NstagesSync.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C4\COREFIFO_C4_0\rtl\vlog\core\corefifo_grayToBinConv.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C4\COREFIFO_C4_0\rtl\vlog\core\corefifo_async.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C4\COREFIFO_C4_0\rtl\vlog\core\corefifo_sync.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C4\COREFIFO_C4_0\rtl\vlog\core\corefifo_fwft.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C4\COREFIFO_C4_0\rtl\vlog\core\corefifo_sync_scntr.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C4\COREFIFO_C4_0\rtl\vlog\core\COREFIFO_C4_COREFIFO_C4_0_LSRAM_top.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C4\COREFIFO_C4_0\rtl\vlog\core\COREFIFO_C4_COREFIFO_C4_0_ram_wrapper.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C4\COREFIFO_C4_0\rtl\vlog\core\COREFIFO.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C4\COREFIFO_C4.v}
read_vhdl -mode vhdl_2008 {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\hdl\Trigger_Unit.vhd}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\Input_Data_Part\Input_Data_Part.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\PF_DPSRAM_C5\PF_DPSRAM_C5_0\PF_DPSRAM_C5_PF_DPSRAM_C5_0_PF_DPSRAM.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\PF_DPSRAM_C5\PF_DPSRAM_C5.v}
read_vhdl -mode vhdl_2008 {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\hdl\Sample_RAM_Block_Decoder.vhd}
read_vhdl -mode vhdl_2008 {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\hdl\Sample_RAM_Block_MUX.vhd}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\Sample_RAM_Block\Sample_RAM_Block.v}
read_vhdl -mode vhdl_2008 {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\hdl\Test_Generator.vhd}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C5\COREFIFO_C5_0\rtl\vlog\core\corefifo_NstagesSync.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C5\COREFIFO_C5_0\rtl\vlog\core\corefifo_grayToBinConv.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C5\COREFIFO_C5_0\rtl\vlog\core\corefifo_async.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C5\COREFIFO_C5_0\rtl\vlog\core\corefifo_sync.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C5\COREFIFO_C5_0\rtl\vlog\core\corefifo_fwft.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C5\COREFIFO_C5_0\rtl\vlog\core\corefifo_sync_scntr.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C5\COREFIFO_C5_0\rtl\vlog\core\COREFIFO_C5_COREFIFO_C5_0_LSRAM_top.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C5\COREFIFO_C5_0\rtl\vlog\core\COREFIFO_C5_COREFIFO_C5_0_ram_wrapper.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C5\COREFIFO_C5_0\rtl\vlog\core\COREFIFO.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C5\COREFIFO_C5.v}
read_vhdl -mode vhdl_2008 {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\hdl\cmd_table_trigger.vhd}
read_vhdl -mode vhdl_2008 {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\hdl\Trigger_Control.vhd}
read_vhdl -mode vhdl_2008 {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\hdl\Trigger_Main.vhd}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\Trigger_Top_Part\Trigger_Top_Part.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\Data_Block\Data_Block.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C0\COREFIFO_C0_0\rtl\vlog\core\corefifo_sync_scntr.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C0\COREFIFO_C0_0\rtl\vlog\core\corefifo_sync.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C0\COREFIFO_C0_0\rtl\vlog\core\corefifo_NstagesSync.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C0\COREFIFO_C0_0\rtl\vlog\core\corefifo_grayToBinConv.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C0\COREFIFO_C0_0\rtl\vlog\core\corefifo_async.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C0\COREFIFO_C0_0\rtl\vlog\core\corefifo_fwft.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C0\COREFIFO_C0_0\rtl\vlog\core\COREFIFO_C0_COREFIFO_C0_0_LSRAM_top.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C0\COREFIFO_C0_0\rtl\vlog\core\COREFIFO_C0_COREFIFO_C0_0_ram_wrapper.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C0\COREFIFO_C0_0\rtl\vlog\core\COREFIFO.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREFIFO_C0\COREFIFO_C0.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREUART_C0\COREUART_C0_0\rtl\vlog\core\Clock_gen.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREUART_C0\COREUART_C0_0\rtl\vlog\core\Rx_async.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREUART_C0\COREUART_C0_0\rtl\vlog\core\Tx_async.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREUART_C0\COREUART_C0_0\rtl\vlog\core\fifo_256x8_54sxa.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREUART_C0\COREUART_C0_0\rtl\vlog\core\CoreUART.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\COREUART_C0\COREUART_C0.v}
read_vhdl -mode vhdl_2008 {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\hdl\UART_RX_Protocol.vhd}
read_vhdl -mode vhdl_2008 {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\hdl\UART_TX_Protocol.vhd}
read_vhdl -mode vhdl_2008 {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\hdl\mko.vhd}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\UART_Protocol\UART_Protocol.v}
read_verilog -mode system_verilog {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\component\work\Top\Top.v}
set_top_level {Top}
map_netlist
read_sdc {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\constraint\Top_derived_constraints.sdc}
check_constraints {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\constraint\synthesis_sdc_errors.log}
write_fdc {C:\VHDL_temp\Digitizer\Digitizer_ver2\Digitizer\designer\Top\synthesis.fdc}
