
// This file was automatically generated by the CoreABC TGI generator

  parameter APB_DWIDTH           = 8;
  parameter APB_SDEPTH           = 10;
  parameter APB_AWIDTH           = 16;
  parameter ICWIDTH              = 5;
  parameter ZRWIDTH              = 0;
  parameter IIWIDTH              = 1;
  parameter IFWIDTH              = 0;
  parameter IOWIDTH              = 1;
  parameter STWIDTH              = 4;
  parameter INITWIDTH            = 11;
  parameter INSMODE              = 0;
  parameter IMEM_APB_ACCESS      = 0;
  parameter ACT_CALIBRATIONDATA  = 1;
  parameter EN_RAM               = 1;
  parameter EN_RAM_ECC           = 0;
  parameter EN_ALURAM            = 0;
  parameter EN_INDIRECT          = 0;
  parameter EN_DATAM             = 2;
  parameter EN_INT               = 0;
  parameter ISRADDR              = 1;
  parameter EN_AND               = 1;
  parameter EN_XOR               = 1;
  parameter EN_OR                = 1;
  parameter EN_ADD               = 1;
  parameter EN_INC               = 1;
  parameter EN_SHL               = 1;
  parameter EN_SHR               = 1;
  parameter EN_CALL              = 1;
  parameter EN_PUSH              = 1;
  parameter EN_ACM               = 0;
  parameter EN_IOREAD            = 1;
  parameter EN_IOWRT             = 1;
  parameter EN_MULT              = 0;
  parameter HDL_license          = "U";
  parameter UNIQ_STRING_LENGTH   = 23;
  parameter UNIQ_STRING          = "COREABC_C0_COREABC_C0_0";
  parameter TESTMODE             = 0;
  parameter FAMILY               = 0;
  parameter ID                   = 0;
  parameter INITDATAWIDTH        = 32;
  parameter MAX_NVMDWIDTH        = 32;
  parameter TESTBENCH            = "User";
  parameter DEBUG                = 1;
  parameter HI_REL               = 0;
  parameter APB_TIMEOUT_COUNT    = 80;
  parameter INVALID_STACK_ACC    = 1;


